billsdjango/reports/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView

from . import views
from . import charts
from .views import units
from .views.changes import ChangesView
from .charts import units as UnitCharts
from billsdjango.accounts.views import ProfileView


urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=False), name='index'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^connections/$', views.ConnectionsList.as_view(), name='connections'),
    url(r'^connections/(?P<connection_id>\d+)/share/$', views.ShareConnection.as_view(), name='share_connection'),
    url(r'^connections/new/$', views.AddConnection.as_view(), name='add_connection'),
    url(r'^connections/(?P<branch>\d+)/$', views.AddCompanyConnection.as_view(), name='add_company_connection'),
    url(r'^bills/(?P<bill_id>\d+)/details/$', views.ViewBillDetails.as_view(), name='view_bill_details'),

    url(r'^units/$', units.Dashboard.as_view(), name='units'),
    url(r'^bills/(?P<bill_id>\d+)/units/$', units.BillUnits.as_view(), name='bill_units'),

    url(r'^bills/changes/$', ChangesView.as_view(), name='changes'),
    url(r'^bills/(?P<conn_id>\d+)/changes/$', ChangesView.as_view(), name='bill_changes'),

    url(r'^bills/charts/current_bills/$', charts.DashboardChart.as_view(), name='dashboard_chart'),
    url(r'^bills/charts/(?P<bill_id>\d+)/details/$', charts.BillDetailsChart.as_view(), name='bill_details_chart'),

    url(r'^units/charts/dashboard/$', UnitCharts.Dashboard.as_view(), name='units_chart'),
    url(r'^bills/(?P<bill_id>\d+)/units/charts$', UnitCharts.BillUnits.as_view(), name='bill_units_chart'),

    url(r'^profile/$', ProfileView.as_view(), name='profile')
)

billsdjango/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'', include('billsdjango.reports.urls')),
    url(r'^accounts/', include('billsdjango.accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

billsdjango/reports/models.py
from decimal import Decimal
from dateutil.relativedelta import relativedelta

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import URLValidator


class ReportModel(models.Model):
     created_on = models.DateTimeField(auto_now_add=True, default=timezone.now)

     class Meta:
         abstract = True


class City(ReportModel):
    short_name = models.CharField(max_length=20) # khi, isb, lhr, rwl
    long_name = models.CharField(max_length=50) # karachi, islamabad, lahore, rawalpindi

    def __unicode__(self):
        return '%s (%s)' % (self.long_name.title(), self.short_name.upper())

    class Meta:
        verbose_name_plural = "Cities"


class Company(ReportModel):
    short_name = models.CharField(max_length=20) # kesc, ptcl, ssgc, kwsb etc
    long_name = models.CharField(max_length=100) # karachi electric supply company, pakistan telecommunication company limited, etc
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return '%s (%s)' % (self.long_name.title(), self.short_name.upper())

    class Meta:
        verbose_name_plural = "Companies"


class Branch(ReportModel):
    city = models.ForeignKey(City)
    company = models.ForeignKey(Company)
    example_image = models.TextField(null=True, blank=True, validators=[URLValidator()])

    def __unicode__(self):
        return '%s (%s) branch of %s (%s)' % (self.company.short_name.upper(), self.company.pk, self.city.long_name, self.city.pk)

    class Meta:
        verbose_name_plural = "Branches"
        unique_together = (
            ('city', 'company'),
        )


class BranchParameters(ReportModel):
    branch = models.ForeignKey(Branch)
    key = models.CharField(max_length=100)
    value = models.CharField(max_length=255)
    comments = models.CharField(max_length=140, blank=True, null=True)

    def __unicode__(self):
        return '%s (%s) of branch %s' % (self.value, self.key, self.branch)

    class Meta:
        verbose_name_plural = "Branch Parameters"
        unique_together = (
            ('branch', 'key'),
        )

class Connection(ReportModel):
    user = models.ForeignKey(User)
    branch = models.ForeignKey(Branch)
    shared_with = models.ManyToManyField(User, related_name='viewers', blank=True)

    def __unicode__(self):
        return '%s connection (id:%s) of %s' % (self.branch.company.short_name.upper(), self.pk, self.user.first_name or self.user.username)

    class Meta:
        verbose_name_plural = "Connections"


class ConnectionParameters(ReportModel):
    connection = models.ForeignKey(Connection)
    key = models.CharField(max_length=100)
    value = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Connection Parameters"
        unique_together = (
            ('connection', 'key'),
        )


class Bill(ReportModel):
    connection = models.ForeignKey(Connection)
    customer_name = models.CharField(max_length=100)
    customer_address = models.CharField(max_length=100, blank=True, null=True)
    billing_date = models.DateField()
    amount = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    dues = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    due_date = models.DateField()
    after_dues = models.DecimalField(max_digits=15, decimal_places=2, default=Decimal('0.00'))
    pdf_url = models.CharField(max_length=255)

    @property
    def prev(self):
        prev_date = self.billing_date - relativedelta(months=1)
        last_month_bill = Bill.objects.filter(connection=self.connection,
                                                billing_date__year=prev_date.year,
                                                billing_date__month=prev_date.month) \
                                        .latest('pk')
        return last_month_bill

    @property
    def amount_change(self):
        try:
            return self.amount - self.prev.amount
        except:
            return ''

    @property
    def amount_percent_change(self):
        try:
            return self.amount_change / self.prev.amount * 100
        except:
            return ''

    def __unicode__(self):
        return '%s bill for %s' % (self.billing_date.strftime('%b %Y'), self.connection)

    class Meta:
        verbose_name_plural = "Bills"


class Units(ReportModel):
    bill = models.OneToOneField(Bill)
    previous_units_date = models.DateField(null=True, blank=True)
    previous_units = models.FloatField()
    current_units_date = models.DateField(null=True, blank=True)
    current_units = models.FloatField()
    adjusted_units = models.FloatField(default=0)
    billable_units = models.FloatField()

    @property
    def prev(self):
        prev_date = self.bill.billing_date - relativedelta(months=1)
        last_month_units = Units.objects.filter(bill__connection=self.bill.connection,
                                                bill__billing_date__year=prev_date.year,
                                                bill__billing_date__month=prev_date.month) \
                                        .latest('pk')
        return last_month_units

    @property
    def change(self):
        try:
            return self.billable_units - self.prev.billable_units
        except:
            return ''

    @property
    def percent_change(self):
        try:
            return self.change / self.prev.billable_units * 100
        except:
            return ''

    @property
    def billable_units_computed(self):
        try:
            return self.current_units - self.previous_units
        except:
            return self.billable_units

    @property
    def adjusted_units_computed(self):
        try:
            return self.billable_units - self.billable_units_computed
        except:
            return self.adjusted_units

    def __unicode__(self):
        return '%s units for %s' % (self.billable_units, self.bill)

    @property
    def price(self):
        expense = self.bill.amount or self.bill.dues or 0
        if self.billable_units <= 0:
            return ''
        return float(expense) / float(self.billable_units)

    @property
    def price_change(self):
        if self.billable_units <= 0 or self.prev.billable_units <= 0:
            return ''
        try:
            prev_expense = self.prev.bill.amount or self.prev.bill.dues or 0
            prev_price = float(prev_expense) / float(self.prev.billable_units)
            return self.price - prev_price
        except:
            return ''

    @property
    def price_percent_change(self):
        try:
            prev_expense = self.prev.bill.amount or self.prev.bill.dues or 0
            return float(self.price_change) / float(prev_expense) * 100
        except:
            return ''

    class Meta:
        verbose_name_plural = "Units"

billsdjango/reports/views/changes.py
from django.db.models import Q
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

from .. import LoginRequiredMixin
from .. import get_utc5_now
from .. import models


class ChangesView(LoginRequiredMixin, TemplateView):
    template_name = 'changes.html'

    def get_context_data(self, **kwargs):
        context = super(ChangesView, self).get_context_data(**kwargs)

        user = User.objects.get(id=self.request.user.id)
        conns = models.Connection.objects.filter(Q(user=user) | Q(shared_with=user)).distinct()

        if conns:
            conn_id = kwargs.get('conn_id', None)
            if not conn_id:
                conn_id = conns.latest('created_on').id

            conn_info = []
            try:
                connection = conns.get(id=conn_id)
            except:
                raise Http404
            conn_info.append({
                'key': 'Id',
                'value': connection.id
            })
            bparams = models.BranchParameters.objects.filter(branch=connection.branch)
            cparams = models.ConnectionParameters.objects.filter(connection=connection)
            for bparam in bparams:
                for cparam in cparams:
                    if bparam.key == cparam.key:
                        conn_info.append({
                            'key': bparam.value,
                            'value': cparam.value
                        })

            last_year_bills = (models.Bill.objects.filter(connection=connection)
                                                  .order_by('-billing_date')[:12])
            context['connections'] = conns
            context['connection_info'] = conn_info
            context['bills'] = last_year_bills
            if last_year_bills:
                context['title'] = '%s (%s) Connection' % (
                                    connection.branch.company.short_name,
                                    last_year_bills[0].customer_name)
            else:
                context['title'] = '%s (%s) Connection' % (
                                    connection.branch.company.short_name,
                                    'Updating...')
        else:
            context['title'] = 'Consolidated View'
        return context

billsdjango/reports/views/units.py
from dateutil.relativedelta import relativedelta

from django.db.models import Q
from django.contrib.auth.models import User
from django.views.generic import TemplateView

from .. import get_utc5_now, LoginRequiredMixin
from .. import models


class Dashboard(LoginRequiredMixin, TemplateView):
    title = 'Unit Consumption'
    template_name = 'units/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)

        month = year = None
        r_date = self.request.GET.get('date')
        if r_date and re.match(r'^\d{2}-\d{4}$', r_date): # validate input :)
            month, year = r_date.split('-')

        user = User.objects.get(id=self.request.user.id)
        companies = models.Company.objects.filter(short_name__in=['k-electric', 'ssgc'])
        connections = models.Connection.objects.filter(Q(branch__company__in=companies),
                                                         Q(user=user) | Q(shared_with=user)) \
                                                .distinct()

        current_billing_date = get_utc5_now() - relativedelta(months=1)

        bills = models.Bill.objects.filter(Q(connection__branch__company__in=companies),
                                            Q(connection__user=user) | Q(connection__shared_with=user))
        if bills:
            latest_bill = bills.latest('billing_date')
            if latest_bill:
                current_billing_date = latest_bill.billing_date

        current_billing_year = year or current_billing_date.strftime('%Y')
        current_billing_month = month or current_billing_date.strftime('%m')

        allbills = {}

        for connection in connections:
            name = connection.branch.company.short_name
            if name not in allbills:
                allbills[name] = []
            bills = (models.Bill.objects.filter(connection=connection,
                                                billing_date__year=current_billing_year,
                                                billing_date__month=current_billing_month)
                                        .order_by('-billing_date'))
            for bill in bills:
                if hasattr(bill, 'units'):
                    allbills[name].append(bill)

        context['r_date'] = r_date
        context['range'] = [current_billing_date - relativedelta(months=m) for m in range(0, 11)]
        context['allbills'] = allbills.iteritems()
        context['title'] = self.title
        return context


class BillUnits(LoginRequiredMixin, TemplateView):
    title = 'Unit Consumption'
    template_name = 'units/bill.html'

    def get_context_data(self, bill_id=None, **kwargs):
        context = super(BillUnits, self).get_context_data(**kwargs)

        selected_bill = None

        bill = models.Bill.objects.get(pk=bill_id)
        if bill.connection.user.id == self.request.user.id:
            selected_bill = bill
        elif bill.connection.shared_with.filter(pk=self.request.user.id).exists():
            selected_bill = bill

        if selected_bill.connection.branch.company.short_name.lower() not in ['k-electric', 'ssgc']:
            return

        try:
            latest_bill = (models.Bill.objects.filter(connection=selected_bill.connection)
                                                .latest('billing_date'))
        except:
            latest_bill = None

        last_year_bills = []
        if latest_bill:
            end_date = latest_bill.billing_date
            start_date = end_date - relativedelta(months=12)
            last_year_bills = (models.Bill.objects.filter(connection=selected_bill.connection,
                                                            billing_date__range=[start_date, end_date])
                                                    .order_by('-billing_date'))

        context['title'] = '%s Units (%s)' % (selected_bill.connection.branch.company.short_name,
                                            selected_bill.customer_name)
        context['chart_name'] = selected_bill.connection.branch.company.short_name
        context['selected_bill'] = selected_bill
        context['last_year_bills'] = last_year_bills
        return context

billsdjango/reports/templates/add_company_connection.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Add New {{ company.short_name }} Bill Connection | Bills.pk{% endblock %}

{% block bodyclass %}add_company_connection{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb">
    <li>{% trans 'Dashboard' %}</li>
    <li>{% trans 'Add New Bill Connection' %}</li>
    <li class="active">Add New {{ company.short_name }} Bill Connection</li>
</ol>
{% endblock %}

{% block header %}
<div id="header">
    {% if branch.example_image %}
    <div id="accordion" class="panel-group" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <h1>
                Add New {{ company.short_name }} Bill Connection
                <br />
                <small>
                    <span class="glyphicon glyphicon-picture"></span>
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Show example
                    </a>
                </small>
            </h1>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                <p style="background: url('{{ branch.example_image }}') no-repeat; height: 400px;" alt="{{ branch }}"></p>
            </div>
        </div>
    </div>
    {% else %}
    <h1>Add New {{ company.short_name }} Bill Connection</h1>
    {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <form action="" method="post" role="form">{% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% for field in form %}
                <div class="form-group">
                    {% if field.name == 'user' %}
                        <input name="{{ field.name }}" placeholder="{{ field.label }}" value="{{ request.user.id }}" class="form-control" type="{% if field.is_hidden %}hidden{% else %}text{% endif %}" />
                    {% else %}
                        <input name="{{ field.name }}" placeholder="{{ field.label }}" value="{% if field.value and not field.is_hidden %}{{ field.value }}{% endif %}" class="form-control" type="{% if field.is_hidden %}hidden{% else %}text{% endif %}" />
                        <p class="help-block">{{ field.help_text }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
    <div class="col-md-6">
    </div>
</div>
{% endblock %}

billsdjango/reports/templates/add_connection.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Add New Bill Connection | Bills.pk{% endblock %}

{% block bodyclass %}add_connection{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb">
    <li>{% trans 'Dashboard' %}</li>
    <li class="active">{% trans 'Add New Bill Connection' %}</li>
</ol>
{% endblock %}

{% block header %}
<div id="header">
    <h1>Add New Bill Connection</h1><br />
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <form action="" method="post" role="form">{% csrf_token %}
            <div class="form-group">
                <select name="{{ form.branch.name }}" value="{% if form.branch.value %}{{ form.branch.value }}{% endif %}" class="form-control input-lg" onchange="form.submit()">
                    <option value="-1">Select Company Branch</option>
                    {% for city, branches in form.branch.field.choices %}
                        <optgroup label="{{ city }}">
                        {% for id, branch in branches %}
                            <option value="{{ id }}">{{ branch.company.long_name }} ({{ branch.company.short_name }})</option>
                        {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
    <div class="col-md-3">
    </div>
</div>
{% endblock %}

billsdjango/reports/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="{% static 'bootstrap-3.1.1-dist/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% block extrastyle %}{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap-3.1.1-dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libs/highcharts-4.0.4/js/highcharts.js' %}"></script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb">
    {% if title %}<li class="active">{{ title }}</li>{% endif %}
</ol>
{% endblock %}

<!-- Container -->
<div class="container">

    {% if not is_popup %}
    <!-- Header -->
    <!--
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% trans 'Welcome,' %}
            <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    -->
    <!-- END Header -->

    {% endif %}

    {% block header %}<div id="header"></div>{% endblock %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">{{ message|capfirst }}</div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}
        <div id="footer" class="text-right">
            <small>Powered by Bills.pk</small>
        </div>
    {% endblock %}
    <br />
</div>
<!-- END Container -->

{% block scripts %}{% endblock %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52365836-2', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

billsdjango/reports/templates/connection_list.html
{% extends "base.html" %}

{% load i18n staticfiles %}

{% block title %}{{ title }} | Bills.pk{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'libs/nvd3/nv.d3.min.css' %}" />
<script type="text/javascript" src="{% static 'libs/d3/d3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libs/nvd3/nv.d3.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('a').filter(function() {
            return $(this).text() === 'Share';
        }).click(function(event) {
            event.preventDefault();
            $('.modal iframe').attr('src', $(this).attr('href'));
            $('.modal').modal();
        });
    });
</script>
{% endblock %}

{% block bodyclass %}connections_list{% endblock %}

{% block content_title %}
    <div class="row content_title">
        <div class="col-md-6">
            {% if title %}<h1>{{ title }} ({{ total_conn }})</h1>{% endif %}
        </div>
    </div>
{% endblock %}

{% block breadcrumbs %}
<ol class="breadcrumb">
    <li class="active">{% trans 'Dashboard' %}</li>
    {% if title %} &rsaquo; {{ title }}{% endif %}
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered">
            {% if allconnections %}
                {% for company, object in allconnections %}
                    <thead>
                        <tr>
                            <th colspan="7">
                                <h4>
                                    {{ company }} ({{ object.connections|length }})</h3>
                                    <div class="pull-right">
                                    </div>
                                </h4>
                            </th>
                        </tr>
                        <tr>
                            <th>Customer Name</th>
                            {% if object.params %}
                                {% for param in object.params %}
                                    <th class="text-right">{{ param.value }}</th>
                                {% endfor %}
                            {% endif %}
                            <th class="">&nbsp;</th>
                            <th class="">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if object.connections %}
                        {% for connection_object in object.connections %}
                        <tr>
                            <td>{{ connection_object.connection.bill_set.all.last.customer_name|default:"Updating..." }}</td>
                            {% if object.params %}
                                {% for bparam in object.params %}
                                    {% for cparam in connection_object.params %}
                                        {% if bparam.key == cparam.key %}
                                            <td class="text-right">{{ cparam.value }}</td>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                            <td class="text-right">
                                {% if connection_object.connection.bill_set.all.last.id %}
                                    <a href="{% url 'view_bill_details' connection_object.connection.bill_set.all.last.id %}" class="">Details</a>
                                {% endif %}
                            </td>
                            <td class="col-md-1">
                                {% if connection_object.user.id == request.user.id %}
                                <a href="{% url 'share_connection' connection_object.connection.id %}" class"">Share</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="7">
                                <div>
                                    You don't have any connections from this company.
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                {% endfor %}
            {% endif %}
        </table>
    </div>
</div>

<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Share</h4>
            </div>
            <div class="modal-body">
                <iframe scrolling="no"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Done</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

billsdjango/reports/templates/navbar.html
<nav class="navbar navbar-default" role="navigation">

  {% if allusers %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <br />
        <form action="" method="post" role="form">{% csrf_token %}
          <div class="form-group">
            <select name="username" class="form-control" onchange="form.submit()">
              {% for u in allusers %}
              <option value="{{ u.username }}" {% if currentuser.id == u.id %}selected="selected"{% endif %}>{{ u.username }}</option>
              {% endfor %}
            </select>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'dashboard' %}">Bills</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'connections' %}">Bill Connections</a>
        </li>
        <li>
          <a href="{% url 'units' %}">Unit Consumption</a>
        </li>
        <li>
          <a href="{% url 'changes' %}">Consolidated View (Ups and Downs)</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome {{ user.first_name|default:user.username|title }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'profile' %}">Profile</a></li>
            <li><a href="{% url 'password_change' %}">Change Password</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
      <div class="pull-right">
        <a href="{% url 'add_connection' %}" class="btn btn-sm btn-success navbar-btn">Add New Bill Connection</a>
      </div>
    </div>
  </div>
</nav>